import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";
import NavbarMiddleware from "./components/NavbarMiddl";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* This navbar is protected using session */}
        {/* <Nav /> */}

        {/* This Middleware navbar is protected using middleware */}
        <NavbarMiddleware />
        {children}
      </body>
    </html>
  );
}
